<template>
    <div>
        <v-btn color="primary" @click="addOutput">Add output variable</v-btn>
        <VariableDialog ref="varDialog" @newVariable="setOutputVariable($event, null)" />
        <h3>The following outputs were generated by your program</h3>
        <v-alert width="800" type="warning" v-if="!result">
            Your program has not been run yet. Output variables will only obtain a value after running the program.
        </v-alert>
        <v-alert width="800" type="success" v-else-if="!result.error">
            Your program ran succesfully!
        </v-alert>
        <v-alert width="800" type="error" v-else>
            Your program produced an error.
            <br />
            {{ result.data }}
        </v-alert>        
        <EnvironmentDisplay :data="outputs" :deleteVar="deleteOutputVariable" />
    </div>
</template>

<script>
import { useAppStore } from '@/store/app';
import { mapState, mapActions } from 'pinia';
import EnvironmentDisplay from './EnvironmentDisplay';
import VariableDialog from './VariableDialog';

export default {
    components: {
        EnvironmentDisplay,
        VariableDialog
    },
    data: () => ({
        // inputs: {},
        types: ['text', 'number', 'boolean', 'list of text', 'list of numbers'],
        defaultValues: {
            text: 'some text',
            number: 0,
            boolean: false,
            'list of text': ['first element'],
            'list of numbers': [0]
        }
    }),
    methods: {
        addOutput() {
            this.$refs.varDialog.showDialog('Add new output variable', newVarName, 'Add Variable',  true);
        },
        setType(i, type) {
            if (type != i.prevType) {
                console.log(i, type);
                i.type = type;
                i.prevType = type;
                i.defaultValue = this.defaultValues[type];
            }
        },
        // deleteVariable(ev) {
        //     delete this.inputs[ev];
        // }
        ...mapActions(useAppStore, ['setOutputVariable', 'deleteOutputVariable']),
    },
    computed: {
        newVarName() {
            return 'output_'+(Object.keys(this.outputs).length + 1);
        },
        ...mapState(useAppStore, ['result', 'outputs']),
    },
};
</script>

<style scoped>
.inputCard {
    max-width: 40em;
}
</style>