<template>
    <div>
        <v-btn color="primary" @click="addOutput">Add output variable</v-btn>
        <VariableDialog ref="varDialog" @newVariable="setOutputVariable($event, null)" />
        <v-alert class="result-alert" width="850" type="warning" v-if="!result">
            Your program has not been run yet. Output variables will only obtain a value after running the program.
        </v-alert>
        <v-alert class="result-alert" width="850" type="success" v-else-if="!result.error">
            Your program ran succesfully!
        </v-alert>
        <v-alert class="result-alert" width="850" type="error" v-else>
            Your program produced an error.
            <br />
            {{ result.data }}
        </v-alert>
        <h3 v-if="!result || (result && result.error)">The following output variable are defined for your program</h3>
        <h3 v-else>The following outputs were generated by your program</h3>
        <EnvironmentDisplay :data="outputs" :deleteVar="deleteVariable" />
        <template v-if="result?.output?.length > 0">
            <h4>Your program printed the following:</h4>
            <v-textarea :model-value="outputText" readonly :rows="5" style="max-width: 50em;" />
        </template>
        <ConfirmDialog ref="confirmDialog" />
    </div>
</template>

<script>
import { useAppStore } from '@/store/app';
import { mapState, mapActions } from 'pinia';
import EnvironmentDisplay from './EnvironmentDisplay';
import ConfirmDialog from './ConfirmDialog.vue';
import VariableDialog from './VariableDialog';


export default {
    components: {
        ConfirmDialog,
        EnvironmentDisplay,
        VariableDialog
    },
    data: () => ({
        // inputs: {},
        types: ['text', 'number', 'boolean', 'list of text', 'list of numbers'],
        defaultValues: {
            text: 'some text',
            number: 0,
            boolean: false,
            'list of text': ['first element'],
            'list of numbers': [0]
        }
    }),
    methods: {
        addOutput() {
            this.$refs.varDialog.showDialog('Add new output variable', this.newVarName, 'Add Variable',  true);
        },
        setType(i, type) {
            if (type != i.prevType) {
                console.log(i, type);
                i.type = type;
                i.prevType = type;
                i.defaultValue = this.defaultValues[type];
            }
        },
        deleteVariable(name) {
            this.$refs.confirmDialog.showDialog(
                'Delete output variable?',
                `Are you sure you want to remove the output variable '${name}'?`,
                'warning',
                () => this.deleteOutputVariable(name)
            );
        },
        ...mapActions(useAppStore, ['setOutputVariable', 'deleteOutputVariable']),
    },
    computed: {
        newVarName() {
            return 'output_'+(Object.keys(this.outputs).length + 1);
        },
        outputText() {
            if (this?.result?.output) {
                return this.result.output.join('\n');
            }
            return '';
        },
        ...mapState(useAppStore, ['result', 'outputs']),
    },
};
</script>

<style scoped>
.inputCard {
    max-width: 40em;
}

.result-alert {
    margin-top: 0.75em;
    margin-bottom: 0.75em;
}
</style>